platform :ios, '11.0'

target 'ParleyExample' do
  use_frameworks!

  pod 'Parley', :path => '../'
  
  pod 'Firebase/Analytics', '~> 7.9.0'
  pod 'Firebase/Messaging', '~> 7.9.0'

  pod 'Wormholy', :configurations => ['Debug']
end
