platform :ios, '12.0'

target 'ParleyExample' do
  use_frameworks!

  pod 'Parley', :path => '../'
  
  pod 'Firebase/Analytics', '~> 7.9.0'
  pod 'Firebase/Messaging', '~> 7.9.0'

  # pod 'Wormholy', :configurations => ['Debug'] # Only for testing
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
